#!/bin/bash

set -Eeu -o pipefail

BUTTON="${button:-}"
export LABEL BUTTON

function generate_news() {
    NEWS=$(/home/dedenbangkit/Scripts/berita)
    LABEL_COLOR=${label_color:-$(xrescat i3xrocks.label.color "#7B8394")}
    VALUE_COLOR=${color:-$(xrescat i3xrocks.value.color "#D8DEE9")}
    VALUE_BG_COLOR=${bg_color:-$(xrescat i3xrocks.value.bg_color "#3b3b3b")}
    VALUE_FONT=${font:-$(xrescat i3xrocks.value.font "JetBrains Mono 10")}
    echo "<span font_desc=\"${VALUE_FONT}\" color=\"${VALUE_COLOR}\" background=\"${VALUE_BG_COLOR}\">$NEWS</span> "
    echo $NEWS > /tmp/news.tmp
    echo "<span font_desc=\"${VALUE_FONT}\" color=\"${VALUE_COLOR}\" background=\"${VALUE_BG_COLOR}\">$NEWS</span> " > /tmp/news.html.tmp
}

if [ "${BUTTON}" == "" ]; then
    generate_news
fi

if [ "x${BUTTON}" == "x1" ]; then
    KWD=$(cat /tmp/news.tmp | cut -d '/' -f2 | sed 's/.*> //' | cut -d '.' -f1) 
    ACTION=$(xrescat i3xrocks.action.berita "firefox --search \"${KWD}\"")
    /usr/bin/i3-msg -q "exec --no-startup-id $ACTION"
    generate_news
fi
